### ISSUE TITLE
Crash when connecting BT device

### ISSUE THREAD

**Issue by jroal** [jroal/a2dpvolume#225]
java.lang.IllegalArgumentException: Service Intent must be explicit: Intent { act=android.bluetooth.IBluetoothA2dp }
	at android.app.ContextImpl.validateServiceIntent(ContextImpl.java:1195)
	at android.app.ContextImpl.bindServiceCommon(ContextImpl.java:1294)
	at android.app.ContextImpl.bindService(ContextImpl.java:1272)
	at android.content.ContextWrapper.bindService(ContextWrapper.java:604)
	 **at a2dp.Vol.service.getIBluetoothA2dp(service.java:1302)**
	at a2dp.Vol.service$6.onFinish(service.java:621)
	at android.os.CountDownTimer$1.handleMessage(CountDownTimer.java:127)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:224)
	at android.app.ActivityThread.main(ActivityThread.java:5526)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by jroal** [comment]
I found this: [https://commonsware.com/blog/2014/06/29/dealing-deprecations-bindservice.html](https://commonsware.com/blog/2014/06/29/dealing-deprecations-bindservice.html).  It works as long as I build to target API 19.  I could do that for a while but it will not last.  It also give natigrams saying I should build for the latest.  I have not figured out how to create an explicit intent that works yet.

**Comment by jroal** [comment]
For now I am setting target API back to 19.  This fixes this issue until I have a need to use a higher target API.

**Comment by jroal** [comment]
OK, now we are stuck.  It is not legal to downgrade an APK once it was published with API 23 or higher.  Anybody who needs this fix will need to unuinstall the app and side load this version (zip below).  Sorry for the hassle.  I am clearly amateur at this.
[A2DPVolume_2.12.6.zip](https://github.com/jroal/a2dpvolume/files/455188/A2DPVolume_2.12.6.zip)

**Comment by jroal** [comment]
Finally figure it out.  Published 2.12.7 to Play Store.  Beta for now.  Please test and let me know any issues.
