### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by tingsu** [jroal/a2dpvolume#252]
version code: 135
version name: 2.12.9

exception trace:

java.lang.RuntimeException: Unable to start activity ComponentInfo{a2dp.Vol/a2dp.Vol.EditDevice}: java.lang.IllegalArgumentException: the bind value at index 1 is null
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
 	at android.os.Handler.dispatchMessage(Handler.java:99)
 	at android.os.Looper.loop(Looper.java:137)
 	at android.app.ActivityThread.main(ActivityThread.java:5103)
 	at java.lang.reflect.Method.invokeNative(Native Method)
 	at java.lang.reflect.Method.invoke(Method.java:525)
 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
 	at dalvik.system.NativeStart.main(Native Method)
 Caused by: java.lang.IllegalArgumentException: the bind value at index 1 is null
 	at android.database.sqlite.SQLiteProgram.bindString(SQLiteProgram.java:164)
 	at android.database.sqlite.SQLiteProgram.bindAllArgsAsStrings(SQLiteProgram.java:200)
 	at android.database.sqlite.SQLiteDirectCursorDriver.query(SQLiteDirectCursorDriver.java:47)
 	at android.database.sqlite.SQLiteDatabase.rawQueryWithFactory(SQLiteDatabase.java:1314)
 	at android.database.sqlite.SQLiteDatabase.queryWithFactory(SQLiteDatabase.java:1161)
 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1032)
 	at android.database.sqlite.SQLiteDatabase.query(SQLiteDatabase.java:1238)
 	at a2dp.Vol.DeviceDB.getBTD(DeviceDB.java:146)
 	at a2dp.Vol.EditDevice.onCreate(EditDevice.java:177)
 	at android.app.Activity.performCreate(Activity.java:5133)
 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)

**Comment by jroal** [comment]
Implemented.  Thanks.
