### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by tingsu** [jroal/a2dpvolume#253]
version code: 135
version name: 2.12.9

exception trace:

java.lang.AbstractMethodError: abstract method not implemented
 	at android.service.notification.NotificationListenerService.onNotificationPosted(NotificationListenerService.java)
 	at a2dp.Vol.NotificationCatcher.onNotificationPosted(NotificationCatcher.java:78)
 	at android.service.notification.NotificationListenerService$INotificationListenerWrapper.onNotificationPosted(NotificationListenerService.java:167)
 	at android.service.notification.INotificationListener$Stub.onTransact(INotificationListener.java:56)
 	at android.os.Binder.execTransact(Binder.java:388)
 	at dalvik.system.NativeStart.run(Native Method)

**Comment by cprhokie** [comment]
In API 19 this super method being called is Abstract.  In newer versions of the API it is no longer abstract but simply does nothing...so fix is to simply not call super.onNotificationPosted.

**Comment by jroal** [comment]
I made that change now in version 2.12.9.2 and tested it on the emulator.  All worked fine. Thanks!
