### ISSUE TITLE
"Exoprt  Field" and   "WindowLeaked".

### ISSUE THREAD

**Issue by YYYSSSHHH** [jroal/a2dpvolume#298]
**Environment Info：**
APK Version: 2.13.0.4
Android simulator version: 6.0.1

**Repro Steps：**
Click "Manage Data".  -->    Click "EXPORT LAST LOCATION DATA" and then app shows "Export Failed".

**Stack Trace：**
[ 07-18 13126:13442 E/A2DP Volume ]
/data/user/0/a2dp.Vol/files/My_Last_Location: open failed: ENOENT (No such file or directory)
java.io.FileNotFoundException: /data/user/0/a2dp.Vol/files/My_Last_Location: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:452)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at a2dp.Vol.ManageData$ExportLocationTask.copyFile(ManageData.java:542)
	at a2dp.Vol.ManageData$ExportLocationTask.doInBackground(ManageData.java:514)
	at a2dp.Vol.ManageData$ExportLocationTask.doInBackground(ManageData.java:490)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:438)
	... 10 more

![3](https://user-images.githubusercontent.com/55122523/126057794-df45c4a0-d686-4f00-b495-fc588bb64334.png)

**Another exception was also caught：**
[ 07-18  13126:13126 E/WindowManager ]
android.view.WindowLeaked: Activity a2dp.Vol.main has leaked window android.widget.PopupWindow$PopupDecorView{fd3df28 V.E...... ......ID 0,0-294,432} that was originally added here
	at android.view.ViewRootImpl.<init>(ViewRootImpl.java:368)
	at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:299)
	at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
	at android.widget.PopupWindow.invokePopup(PopupWindow.java:1258)
	at android.widget.PopupWindow.showAsDropDown(PopupWindow.java:1110)
	at android.widget.ListPopupWindow.show(ListPopupWindow.java:658)
	at com.android.internal.view.menu.MenuPopupHelper.tryShow(MenuPopupHelper.java:170)
	at android.widget.ActionMenuPresenter$OpenOverflowRunnable.run(ActionMenuPresenter.java:997)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5539)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:745)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:635)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Maybe can be solved with reference to this**: https://stackoverflow.com/questions/2850573/activity-has-leaked-window-that-was-originally-added

**Do you judge this as a defect?**

**Comment by jroal** [comment]
I will keep this on the list but I have no plans to do any work on this app anytime soon.
